/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    colors: {
      'sc-darker': '#151613',
      'sc-dark': '#20201d',
      'sc-darkless': '#2b2b27',
      'sc-black': '#1d201d',
      'sc-text': '#1d201d',
      'sc-slate': '#3b413a',
      'sc-muted': '#777f76',
      'sc-smoke': '#d5d8d5',
      'sc-sunken': '#d5d8d5',
      'sc-snow': '#f5f5f4',
      'sc-background': '#f5f5f4',
      'sc-white': '#ffffff',
      'sc-sheet': '#ffffff',
      'sc-elevated': '#ffffff',
      'sc-pink': '#ff62dc',
      'sc-orange': '#ff5b00',
      'sc-yellow': '#f7ff00',
      'sc-green': '#28ff00',
      'sc-cyan': '#00ffff',
      'sc-blue': '#00a4ff',
      'sc-purple': '#c210ff',
      'sc-red': '#ec3750',
      'sc-progress': '#ec3750',
    },
  },
  plugins: [],
}
